x = float(input ("Enter first number: "))
y = float(input ("Enter second number: "))
result1 = x + y
result2 = x - y
result3 = x * y
result4 = x / y
print(x,"+", y, "=",result1)
print(x,"-", y, "=",result2)
print(x,"*", y, "=",result3)
print(x,"/", y, "=",result4)
